FROM dxflrs/garage:v2.1.0 AS garage

FROM debian:trixie
COPY --from=garage /garage /bin/garage
COPY ./garage/container-entrypoint.sh /bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
CMD ["garage", "server"]
